### ISSUE TITLE
[Q] Usage

### ISSUE THREAD

**Issue by CrystalMethod** [servall/app-config#1]
Please forgive my ignorance. I'm a typescript beginner. I managed to generate my config types.

config.ts
```
...
export interface Config {
  database: Database;
  server:   Server;
}
...
import '@servall/app-config';
// augment the default export from app-config
declare module '@servall/app-config' {
  export interface ExportedConfig extends Config {}
}
```

So how do I use these types in my sources? In the docs I can read: "Alternatively, if you don't want the config to be loaded on import" How do I load config "on import"?

**Comment by joelgallant** [comment]
You should be good to go. Provided that the `config.ts` file is in your `include` part of `tsconfig.json` (wildcards are okay - https://github.com/servall/app-config/blob/master/tsconfig.json#L13 for example), then you can use app-config like any node module.

```typescript
import config from '@servall/app-config';
```

should yield the configuration object, and have the typescript type that you generated.

**Comment by mordof** [comment]
@CrystalMethod   https://www.geekabyte.io/2017/10/understanding-declaration-files-in.html  here's some in-depth details about declaration files for typescript.

Essentially the `config.ts` file that gets generated informs typescript of what the types will be, when they get imported. 

This section:
```
declare module '@servall/app-config' {
  export interface ExportedConfig extends Config {}
}
```
is the part that says "when `@servall/app-config` gets imported, this is the types it has".

**Comment by joelgallant** [comment]
@CrystalMethod did you ever manage to get something working?
